In [1]:
from sentence_transformers import SentenceTransformer
import torch

Using Different Models

In [2]:
model = SentenceTransformer('distilbert-base-nli-mean-tokens')
minimodel=SentenceTransformer('all-MiniLM-L6-v2')
# mpnet=SentenceTransformer('sentence-transformers/all-mpnet-base-v2')
# model = TFBertModel.from_pretrained("./pt_model/my_pytorch_model.bin", from_pt=True, config=config)

In [3]:
sentences = [
    "the fifty mannequin heads floating in the pool kind of freaked them out",
    "she swore she just saw her sushi move",
    "he embraced his new life as an eggplant",
    "my dentist tells me that chewing bricks is very bad for your teeth",
    "the dental specialist recommended an immediate stop to flossing with construction materials"
]
embeddings=model.encode(sentences)
membeddings=minimodel.encode(sentences)

In [4]:
import numpy as np
from sentence_transformers.util import cos_sim

In [5]:
sim1=np.zeros((len(sentences),len(sentences)))
sim2=np.zeros((len(sentences),len(sentences)))

In [6]:
for i in range(len(sentences)):
    sim1[i:,i]=cos_sim(embeddings[i],embeddings[i:])
    sim2[i:,i]=cos_sim(membeddings[i],membeddings[i:])

Cosine Simmilarity using model1

In [7]:
sim1

array([[0.99999982, 0.        , 0.        , 0.        , 0.        ],
       [0.47645319, 1.00000012, 0.        , 0.        , 0.        ],
       [0.15947187, 0.42819723, 1.        , 0.        , 0.        ],
       [0.41520053, 0.42834941, 0.1513149 , 1.00000012, 0.        ],
       [0.29242051, 0.42459354, 0.22014709, 0.63346052, 1.        ]])

Cosine Simmilarity using model2

In [8]:
sim2

array([[ 1.00000012,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.21621107,  1.00000024,  0.        ,  0.        ,  0.        ],
       [ 0.03266479,  0.18411851,  1.00000012,  0.        ,  0.        ],
       [-0.05884855,  0.07821246,  0.14794004,  1.00000012,  0.        ],
       [ 0.08289957,  0.0291306 ,  0.08819296,  0.42382169,  1.00000012]])

Embeddings_Of_DataSet

In [9]:
import pandas as pd
ds=pd.read_csv('medium_Data.csv.xls')
ds

Titles            Authors  \
0    Please Consider the Racial Impact of Your Hall...       Savala Nolan   
1    That Time We Burned Down Players’ Houses in Ul...         Tim Cotten   
2    The Wonderful Outcome of the Ice Bucket Challenge        Jamie Cohen   
3              Why Should You Care About the Bar Exam?          Dan Canon   
4        Please Don’t Tell My Daughter She’s Beautiful      Kerala Taylor   
..                                                 ...                ...   
304   How I Kept My Sense of Humor Through Vision Loss       Nancy Solari   
305  The true scientific meaning of Mercury enterin...       Ethan Siegel   
306  The Feelings Monster, building a character wit...   Microsoft Design   
307  Feeling Overwhelmed? You Need an MVD—That’s Mi...  Rebecca Pendleton   
308        Type Casting — or: The Comic Sans of Errors       Boris Müller   

            Dates                                              Links  \
0          Oct 17  https://momentum.medium.com/i-beg-you-consider...   
1           Oct 3  https://blog.cotten.io/that-time-we-burned-dow...   
2          Sep 30  https://newanddigital.medium.com/the-long-payo...   
3          Sep 27  https://medium.com/i-taught-the-law/why-should...   
4          Oct 11  https://keralataylor.medium.com/please-dont-te...   
..            ...                                                ...   
304        Sep 15  https://betterhumans.pub/how-i-kept-my-sense-o...   
305        Sep 15  https://medium.com/starts-with-a-bang/the-true...   
306         Sep 6  https://medium.com/microsoft-design/the-feelin...   
307  May 27, 2021  https://index.medium.com/feeling-overwhelmed-y...   
308   Mar 9, 2019  https://borism.medium.com/type-casting-or-the-...   

                                              Contents  
0    Oh, it’s that time of year again! So here is a...  
1    Ultima Online is celebrating its 25th annivers...  
2    The water had to be ice cold and you had to be...  
3    You didn’t take the bar exam. That’s probably ...  
4    I have two beautiful children.I might be biase...  
..                                                 ...  
304  My diagnosis of retinitis pigmentosa at age 16...  
305  Throughout almost all of the year, you can see...  
306  On designing for mental health and the power o...  
307  I’\nm a product director at a corporate financ...  
308  A\ncommon question in my first-year design sem...  

[309 rows x 5 columns]

In [10]:
model=SentenceTransformer('sentence-transformers/multi-qa-mpnet-base-dot-v1')

In [11]:
embeddings=model.encode(ds['Titles'])
embeddings

array([[-0.15904112, -0.02815423, -0.34769464, ..., -0.05652945,
        -0.25248212, -0.20429754],
       [-0.02089733, -0.07984428, -0.3048733 , ...,  0.16599381,
        -0.28794917,  0.14395127],
       [ 0.19895129,  0.01414733, -0.44468006, ..., -0.15330118,
         0.18584459, -0.14877291],
       ...,
       [-0.07744548, -0.01752455, -0.28358787, ...,  0.07210062,
        -0.12631127, -0.14551297],
       [-0.26691023, -0.38169003, -0.2883259 , ..., -0.19347322,
         0.01754419, -0.16607647],
       [ 0.07269135, -0.47379884, -0.10616846, ...,  0.0302386 ,
         0.00621203,  0.05653273]], dtype=float32)

In [12]:
# sim=cos_sim(embeddings[304],embeddings[306])
xb=embeddings
xb=xb[:600]
xq=[]
